import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SessionWrapper from "./components/SessionWrapper";
import ScrollHandler from "./components/ScrollHandler";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Opulenza shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <SessionWrapper >
      <body
        // className={inter.className }
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScrollHandler />
        <Navbar/>
        <ScrollHandler />
        {children}
        {/* <div className="absolute"> */}
        <Footer/>
        {/* </div> */}
      </body>
      </SessionWrapper>
    </html>
  );
}
